config/routes.rb
Rails.application.routes.draw do

  # The Bawz
  root 'polls#index'

  # Users Yo
  devise_for :users, path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register' }

  resources :polls do
    resources :questions
    resources :replies, only: [:new, :create]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    else
      # Polls 
      can :read, Poll
      can :create, Poll
      can :update, Poll do |poll|
        poll.try(:user) == user
      end
      can :destroy, Poll do |poll|
        poll.try(:user) == user
      end
      can :create_question, Poll do |poll|
        poll.try(:user) == user
      end
    end
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :reply
  belongs_to :question
  belongs_to :possible_answer
end

app/models/poll.rb
class Poll < ActiveRecord::Base

  # Validations
  validates :title, presence: true

  # Associations
  belongs_to :user
  has_many :questions
  has_many :replies

  # Poll Serializer
  def serialize_for_graph
    PollSerializer.count_per_month(self).to_json
  end

end

app/models/possible_answer.rb
class PossibleAnswer < ActiveRecord::Base
  
  # Associations
  belongs_to :question

end

app/models/question.rb
class Question < ActiveRecord::Base

  # Associations 
  belongs_to :poll
  has_many :possible_answers
  has_many :answers

  accepts_nested_attributes_for :possible_answers, reject_if: proc { |attributes| attributes['title'].blank? }

  def serialize_for_graph
    PollSerializer.answers_per_question(self).to_json
  end

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  
  # Associations
  belongs_to :poll
  has_many :answers

  accepts_nested_attributes_for :answers
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Associations
  has_many :polls

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Your application controller will need to know what to do
  # if a CanCan exception is thrown
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, notice: exception.message
  end

  # ActiveModel::ForbiddenAttributesError CanCan Workaround
  before_filter do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << []
    devise_parameter_sanitizer.for(:account_update) << []
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  before_action :set_poll, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource except: :create

  def index
    @polls = current_user.polls.all
  end

  def show
  end

  def new
    @poll = current_user.polls.build
  end

  def edit
  end

  def create
    @poll = current_user.polls.build(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_poll
      @poll = Poll.find(params[:id])
    end

    def poll_params
      params.require(:poll).permit(:title)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :set_poll
  before_action :set_kind_questions
  before_action :authenticate_user!

  def index
    @questions = Question.all
  end

  def show
  end

  def new
    @question = @poll.questions.build 
    5.times do 
      @question.possible_answers.build
    end
  end

  def edit
  end

  def create
    @question = @poll.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @poll, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:title, :kind, :poll_id, possible_answers_attributes: [ :title, :question_id])
    end

    def set_poll
      @poll = Poll.find(params[:poll_id])
    end

    def set_kind_questions
      @kind_options = [
        [ "Open Answer", "open" ],
        [ "Multiple Choice", "choice" ]
      ]
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def new
    @poll = Poll.find(params[:poll_id])
    @reply = @poll.replies.build

    @poll.questions.each { |question| @reply.answers.build(question: question) }
  end

  def create
    @poll = Poll.find(params[:poll_id])
    @reply = @poll.replies.build(reply_params)

    if @reply.save 
      redirect_to @poll, notice: 'Thank you for taking the poll.'
    else
      render :new
    end
  end

private

  def reply_params
    params.require(:reply).permit(:poll_id, { 
      answers_attributes: [ :value, :question_id, :reply_id, :possible_answer_id ] })
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-static-top
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        Betakix
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          = link_to 'Home', root_path
        %li
          %a{:href => "#"} Link
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Dropdown
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li
              %a{:href => "#"} Action
            %li
              %a{:href => "#"} Another action
            %li
              %a{:href => "#"} Something else here
            %li.divider
            %li
              %a{:href => "#"} Separated link
            %li.divider
            %li
              %a{:href => "#"} One more separated link
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li= link_to "Account Settings", edit_user_registration_path
          %li= link_to "Log out", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Sign in", new_user_session_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Betakix</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Betakix
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'https://www.google.com/jsapi', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      = content_tag :div, flash[:notice], class: 'alert alert-success' if flash[:notice]
      = content_tag :div, flash[:errors], class: 'alert alert-danger' if flash[:error]
      = yield 
    = yield :footer

app/views/polls/_form.html.haml
= form_for @poll do |f|
  - if @poll.errors.any?
    #error_explanation
      %h2= "#{pluralize(@poll.errors.count, "error")} prohibited this poll from being saved:"
      %ul
        - @poll.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/polls/_stats.html.haml
#polls_per_month
  :javascript
    var selector = '#polls_per_month';
    var data = #{@poll.serialize_for_graph}
    Graph.instances.push(new Graph(selector, data, 'column'));

#answers_per_question
  .row
    - @poll.questions.each do |question|
      - if question.kind == "choice"
        .col-md-6{id: "answer_per_question_#{question.id}"};
        :javascript
          var selector = "#answer_per_question_#{question.id}";
          var data = #{question.serialize_for_graph};
          Graph.instances.push(new Graph(selector, data, 'pie'));


- content_for :footer do
  :javascript
    google.load('visualization', '1.0', {'packages':['corechart']});

    // Set a callback to run when the Google Visualization API is loaded.
    google.setOnLoadCallback(function () {
      Graph.instances.forEach(function(instance){
        instance.render();
      });
    });

app/views/polls/edit.html.haml
%h1 Editing poll

= render 'form'

= link_to 'Show', @poll
\|
= link_to 'Back', polls_path

app/views/polls/index.html.haml
%h1 Listing polls

%table
  %tr
    %th Title
    %th
    %th
    %th
    %th

  %ul
    - @polls.each do |poll|
      %li
        %p= link_to poll.title, poll
        %p.btn-group.btn-group-xs
          - if can? :edit, poll
            = link_to 'Edit', edit_poll_path(poll), class: 'btn btn-default'
          = link_to 'Add Question', new_poll_question_path(poll), class: 'btn btn-default'
          = link_to 'Answer', new_poll_reply_path(poll), class: 'btn btn-default'
          - if can? :create_question, poll
            = link_to 'Delete', poll, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'

-# %br

-# = link_to 'New Poll', new_poll_path, class: 'btn btn-primary'

app/views/polls/new.html.haml
%h1 New poll

= render 'form'

= link_to 'Back', polls_path

app/views/polls/show.html.haml
%p
  %h1= @poll.title

%div{:role => "tabpanel"}
  / Nav tabs
  %ul.nav.nav-tabs{:role => "tablist"}
    %li.active{:role => "presentation"}
      = link_to 'Questions', '#tab-questions', data: { toggle: 'tab' } 

    %li{:role => "presentation"}
      = link_to 'Replies', '#tab-replies', data: { toggle: 'tab' } 

    %li{:role => "presentation"}
      = link_to 'Statistics', '#tab-statistics', data: { toggle: 'tab' } 

  .tab-content
    // Questions Tab
    #tab-questions.tab-pane.active{:role => "tabpanel"} 
      %h2 Questions

      %ul
        - @poll.questions.each do |question|
          %li
            =question.title
            %ul 
              - question.possible_answers.each do |answer|
                %li= answer.title

      %p.btn-group.btn-group-xs
        - if can? :edit, @poll
          = link_to 'Edit', edit_poll_path(@poll), class: 'btn btn-default'
        = link_to 'Back', polls_path, class: 'btn btn-default'
        - if can? :create_question, @poll
          = link_to 'Add Question', new_poll_question_path(@poll), class: 'btn btn-default'


    // Replies Tab
    #tab-replies.tab-pane{:role => "tabpanel"}
      %h2 Replies
      - @poll.replies.each do |reply|
        .row
          .col-md-6
            .panel.panel-default
              .panel-heading.text-right
                = time_ago_in_words reply.created_at
                ago
              .panel-body
                %dl
                  - reply.answers.each do |answer|
                    %dt= answer.question.title
                    %dd
                      = answer.value.present? ? answer.value : answer.possible_answer.title

    // Statistics Tab
    #tab-statistics.tab-pane{:role => "tabpanel"} 
      = render "stats"

app/views/questions/_form.html.haml
= form_for [@poll, @question]do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'

  .form-group
    = f.label :kind
    %br
    - @kind_options.each do |option|
      %label
        = f.radio_button :kind, option[1]
        = option[0]
  
  .form-group
    = f.fields_for :possible_answers do |c|
      %p
        =c.text_field :title,  class: 'form-control', placeholder: 'Possible Answer'

  .form-group
    = f.submit 'Save', class: 'btn btn-primary'

app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Show', @question
\|
= link_to 'Back', questions_path

app/views/questions/index.html.haml
%h1 Listing questions

%table
  %tr
    %th Title
    %th Kind
    %th Poll
    %th
    %th
    %th

  - @questions.each do |question|
    %tr
      %td= question.title
      %td= question.kind
      %td= question.poll
      %td= link_to 'Show', [@poll, question] 
      %td= link_to 'Edit', edit_poll_question_path(@poll, question)
      %td= link_to 'Destroy', [@poll, question], :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/questions/new.html.haml
%h1 New question

= render 'form'

= link_to 'Back', @poll 

app/views/questions/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @question.title
%p
  %b Kind:
  = @question.kind
%p
  %b Poll:
  = @question.poll

= link_to 'Edit', edit_question_path(@question)
\|
= link_to 'Back', questions_path

app/views/replies/_choice.html.haml
= c.label :value, c.object.question.title
- c.object.question.possible_answers.each do |answer|
  .radio
    %label
      = answer.title
      = c.radio_button :possible_answer_id, answer.id
      = c.hidden_field :question_id

app/views/replies/_open.html.haml
%p
  %label= c.object.question.title
  .form-group
    = c.text_field :value, class: 'form-control'
    = c.hidden_field :question_id

app/views/replies/new.html.haml
%h1= @poll.title

= form_for [@poll, @reply] do |f|

  .form-group
    = f.fields_for :answers do |c|
      .form-group
        = render c.object.question.kind, c: c

  .form-group
    = f.submit "Finish Poll", class: 'btn btn-primary'